deb packaging of murmur corrected

diff --git a/debian/ndn-mumble-server.postinst b/debian/ndn-mumble-server.postinst
--- a/debian/ndn-mumble-server.postinst
+++ b/debian/ndn-mumble-server.postinst
@@ -1,5 +1,5 @@
 #! /bin/sh
-# postinst script for ndn-ndn-mumble-server
+# postinst script for ndn-mumble-server
 
 set -e
 
@@ -20,60 +20,60 @@ set -e
 case "$1" in
 	configure)
 		# Add user and permanent directories
-		adduser --system --quiet --home /var/lib/ndn-ndn-mumble-server --group ndn-mumble-server
-		[ -d /var/lib/ndn-ndn-mumble-server ] || mkdir /var/lib/ndn-mumble-server
-		chmod 0750 /var/log/ndn-ndn-mumble-server
-		chmod 0750 /var/lib/ndn-ndn-mumble-server
-		chown ndn-ndn-mumble-server:adm /var/log/ndn-mumble-server
-		chown ndn-ndn-mumble-server:ndn-mumble-server /var/lib/ndn-mumble-server
-		if [ -f /etc/ndn-ndn-mumble-server.ini ]; then
-			chmod 0640 /etc/ndn-ndn-mumble-server.ini
-			chown root:ndn-ndn-mumble-server /etc/ndn-mumble-server.ini
+		adduser --system --quiet --home /var/lib/ndn-mumble-server --group ndn-mumble-server
+		[ -d /var/lib/ndn-mumble-server ] || mkdir /var/lib/ndn-mumble-server
+		chmod 0750 /var/log/ndn-mumble-server
+		chmod 0750 /var/lib/ndn-mumble-server
+		chown ndn-mumble-server:adm /var/log/ndn-mumble-server
+		chown ndn-mumble-server:ndn-mumble-server /var/lib/ndn-mumble-server
+		if [ -f /etc/ndn-mumble-server.ini ]; then
+			chmod 0640 /etc/ndn-mumble-server.ini
+			chown root:ndn-mumble-server /etc/ndn-mumble-server.ini
 		fi
 		# Workaround for when this was in .dirs
-		[ -d /var/run/ndn-ndn-mumble-server ] && chown ndn-mumble-server:adm /var/run/ndn-mumble-server
+		[ -d /var/run/ndn-mumble-server ] && chown ndn-mumble-server:adm /var/run/ndn-mumble-server
 
 		# Ensure the file we put in /etc/dbus-1/system.d is loaded
-		# or ndn-ndn-mumble-server will fail to bind to dbus.
+		# or ndn-mumble-server will fail to bind to dbus.
 		invoke-rc.d --quiet dbus force-reload || true
 
 		# Update /etc/default file based on config
-		if [ -f /etc/default/ndn-ndn-mumble-server ] ; then
-			db_get ndn-ndn-mumble-server/start_daemon
+		if [ -f /etc/default/ndn-mumble-server ] ; then
+			db_get ndn-mumble-server/start_daemon
 			if [ "$RET" = "true" ] ; then
 				DAEMON_START=1
 			else
 				DAEMON_START=0
 			fi
-			if grep -E ^MURMUR_DAEMON_START= /etc/default/ndn-ndn-mumble-server > /dev/null; then
-				perl -pi -w -e "s/^MURMUR_DAEMON_START=.+$/MURMUR_DAEMON_START=$DAEMON_START/g" /etc/default/ndn-ndn-mumble-server
+			if grep -E ^MURMUR_DAEMON_START= /etc/default/ndn-mumble-server > /dev/null; then
+				perl -pi -w -e "s/^MURMUR_DAEMON_START=.+$/MURMUR_DAEMON_START=$DAEMON_START/g" /etc/default/ndn-mumble-server
 			else
-				echo "MURMUR_DAEMON_START=$DAEMON_START" >> /etc/default/ndn-ndn-mumble-server
+				echo "MURMUR_DAEMON_START=$DAEMON_START" >> /etc/default/ndn-mumble-server
 			fi
 
-			db_get ndn-ndn-mumble-server/use_capabilities
+			db_get ndn-mumble-server/use_capabilities
 			if [ "$RET" = "true" ] ; then
 				USE_CAPABILITIES=1
 			else
 				USE_CAPABILITIES=0
 			fi
-			if grep -E ^MURMUR_USE_CAPABILITIES= /etc/default/ndn-ndn-mumble-server > /dev/null; then
-				perl -pi -w -e "s/^MURMUR_USE_CAPABILITIES=.+$/MURMUR_USE_CAPABILITIES=$USE_CAPABILITIES/g" /etc/default/ndn-ndn-mumble-server
+			if grep -E ^MURMUR_USE_CAPABILITIES= /etc/default/ndn-mumble-server > /dev/null; then
+				perl -pi -w -e "s/^MURMUR_USE_CAPABILITIES=.+$/MURMUR_USE_CAPABILITIES=$USE_CAPABILITIES/g" /etc/default/ndn-mumble-server
 			else
-				echo "MURMUR_USE_CAPABILITIES=$USE_CAPABILITIES" >> /etc/default/ndn-ndn-mumble-server
+				echo "MURMUR_USE_CAPABILITIES=$USE_CAPABILITIES" >> /etc/default/ndn-mumble-server
 			fi
 		else
-			echo "/etc/default/ndn-ndn-mumble-server not found, configuration failed." >&2
+			echo "/etc/default/ndn-mumble-server not found, configuration failed." >&2
 		fi
 
 		# Update SuperUser password based on config.
 		# When set, clear it from config as it can't be queried and the user is
 		# likely to update it outside of debconf.
-		db_get ndn-ndn-mumble-server/password
+		db_get ndn-mumble-server/password
 		if [ "$RET" != "" ] ; then
-			echo $RET | su ndn-ndn-mumble-server -s /bin/sh -c "/usr/sbin/murmurd -ini /etc/ndn-mumble-server.ini -readsupw"
+			echo $RET | su ndn-mumble-server -s /bin/sh -c "/usr/sbin/murmurd -ini /etc/ndn-mumble-server.ini -readsupw"
 			if [ $? = 0 ] ; then
-				db_set ndn-ndn-mumble-server/password ""
+				db_set ndn-mumble-server/password ""
 			else
 				echo "Failed to set SuperUser password." >&2
 			fi
